apiVersion: apps/v1
kind: Deployment
metadata:
  name: saft-validator
  namespace: saft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saft-validator
  template:
    metadata:
      labels:
        app: saft-validator
    spec:
      containers:
      - name: saft-validator
        image: virgiliofilhos/saft-validator:1.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
